# Generated by Django 5.0.2 on 2024-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('workout_type', models.CharField(max_length=100)),
                ('workout_details', models.TextField()),
            ],
        ),
    ]
